# Generated by Django 4.1.1 on 2022-10-26 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(db_column='date')),
                ('image', models.URLField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField(db_column='date')),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_for_adults', models.BooleanField(default=False)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.URLField(null=True)),
                ('thumbnail', models.URLField(editable=False, null=True)),
                ('categories', models.ManyToManyField(related_name='series', to='movies.category')),
                ('user', models.ManyToManyField(blank=True, related_name='favorite_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum season for any series is 1')])),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.serial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField(db_column='date')),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_for_adults', models.BooleanField(default=False)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('length', models.CharField(max_length=6)),
                ('image', models.URLField(null=True)),
                ('thumbnail', models.URLField(editable=False, null=True)),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.category')),
                ('user', models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField(db_column='date')),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_for_adults', models.BooleanField(default=False)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum season for any episode is 1')])),
                ('length', models.CharField(max_length=6)),
                ('guest_actors', models.ManyToManyField(blank=True, related_name='episodes', to='movies.actor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
