# Generated by Django 4.1.1 on 2022-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_user_serial_user_alter_actor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
