# Generated by Django 4.1.1 on 2022-10-04 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_episode_thumbnail_movie_thumbnail_serial_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='episodes',
            field=models.ManyToManyField(blank=True, related_name='guest_actors', to='movies.episode'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='actors', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='actors', to='movies.serial'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='trailer_url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serial',
            name='thumbnail',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='trailer_url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='favorite_series', to=settings.AUTH_USER_MODEL),
        ),
    ]
