# Generated by Django 4.1.1 on 2022-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_actor_episodes_alter_actor_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(default=120, max_length=6),
            preserve_default=False,
        ),
    ]
