# Generated by Django 4.1.1 on 2022-10-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_episode_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='thumbnail',
        ),
    ]
